### ISSUE TITLE
[지원] 프로젝트 모집 코멘트 등록 / 대댓글작성

### ISSUE THREAD

**Issue by loveAlakazam** [toy-squad/toy-squad-nest#35]
<img width="792" alt="image" src="https://github.com/toy-squad/toy-squad-nest/assets/36457434/b4783275-012b-48f0-b774-8aa7122ebe21">

- 코멘트 작성: 로그인한 유저만 작성할 수 있음.
- 코멘트에 대한 답글: 프로젝트 생성자/ 매니저 가 작성할 수 있음.
   '답글쓰기' 는 프로젝트 생성자/매니저 만 작성가능
- 댓글(혹은 답글) 수정/삭제는 작성자 본인만 가능

**Comment by jskjw157** [comment]
<img width="294" alt="image" src="https://github.com/toy-squad/toy-squad-nest/assets/69754601/20cdcd21-876c-4efd-a1ba-651843a11408">
</br>
[ERD](https://www.erdcloud.com/d/q6KCjneW3KnzbDr9R)
</br>
</br>
* 댓글/답글 작성은 로그인한 유저만 작성할 수 있음.
</br>
* 댓글/답글 수정/삭제는 작성자 본인만 가능
</br>
* 대댓글 기능
</br>
* 대댓글 기능을 위해 부모 댓글과 자식 댓글을 지정한다. (부모댓글 : 자식댓글 = 1:N) 
</br>
* 부모 댓글이 없으면 댓글 있으면 답글
</br>
* 부모 댓글이 있으면 부모 댓글의 id, 자식 댓글이 있으면 자식 댓글의 id []
</br>
 * 해시태그 기능
 </br>
 * 댓글 내용에 유저를 지정하는 해시태그 기능
 </br>
 * 해시태그가 있으면 해시태그 유저 id
  </br>
* 좋아요수, 싫어요수 추후 기능 추가 예정
 </br>
* 댓글:프로젝트 = N:1
 </br>
* 댓글:유저 = N:1
 </br>
