### ISSUE TITLE
[은강] 코멘트 개편 -  마이페이지 / 유저관리 : 받은 댓글 / 답글

### ISSUE THREAD

**Issue by loveAlakazam** [toy-squad/toy-squad-nest#75]
## 마이페이지 댓글/답글 작성

<img width="991" alt="스크린샷 2024-02-22 오전 1 35 58" src="https://github.com/toy-squad/toy-squad-nest/assets/36457434/fe4d727c-bd4c-48fc-b7a9-2dba4984b667">

기획회의 내용 (2024.02.29 오후 8시 45분) ->  댓글과 답글은 로그인 유저가 작성한 댓글과 답글이며 작성한 댓글을 편리하게 수정/삭제를 할 수 있도록 기획한거였음. (댓글 알림 용도가 아님)

- [x] 마이페이지 댓글/답글 데이터 연동 (2024.03.02)

---

## 추후 해야할 것...

- [x] 마이페이지 댓글/답글 데이터 연동 테스트
- [x] 비회원은 (프론트호스트/mypage/*) 페이지는 접근을 하지 못하도록 pre-interceptor (aop)가 구현 필요. 
   => 프론트엔드 지웅님 담당

---

- 연관이슈: #74 - 마이페이지 / 유저관리 : 받은 좋아요 / 누른 좋아요

**Comment by loveAlakazam** [comment]
@godboy4256 
지웅님 안녕하세요.
마이페이지에 댓글/답글 데이터 연동하려고하다가
기획의 방향에 맞는지 확인후에 개발하려고 질문했습니다.

위의 이미지에서 "김철수 님의
댓글에 남긴 답글입니다" 부분에 대해서 질문이 있는데 헷갈려서 설명이 필요할거같아서 코맨트 드립니다.

저기서 네임 김철수님의 댓글 이 
댓글 작성자이자 위이미지의 마이페이지의 로그인한 유저를 의미하는걸까요?

아니면
김철수 라는 타인이 작성을하고 그에대한 답글인가요? 그러면 댓글과 답글 작성했다고 알림받는 사람이 로그인한 유저인거 같은데

로그인한 유저는 프로잭트 관리자인가요?
조금 헷갈려서요 ㅎㅎ 시간되시면 설명을 여기에 해주시거나 디코로 해쥬시면 됩니다

**Comment by loveAlakazam** [comment]
> @loveAlakazam
> 
> 네, 김철수 라는 타인이 작성을 하고 그에 대한 답글이 맞고, 로그인한 유저는 그냥 답글을 남긴거고, 꼭 프로젝트 관리자는 아닙니다. 프로젝트 관리자가 아니어도 댓글에 답글을 남길수 있습니다.
> 
> 정리) 프로젝트 모집글 -> 다른 유저가 모집글에 대한 댓글 작성 -> 또 다른 유저(프로젝트 관련자가 아니라도 모든 유저가 다 작성 가능)가 댓글을 보고 답글 작성 -> 댓글, 답글을 작성한 유저의 마이페이지에 자신이 작성한 댓글 , 답글 목록이 생성됨.

아 이해했습니다. 
프로젝트 관계자여부 상관없이
본인이 작성한 댓글과 해당댓글에 대한 답글이군요.

저희가 코멘트 종류가 세종류인데요
C(일반댓글) , R(답글) , M(멘션표기 답글) 이렇게 3종류인데 

마이페이지에 답글작성에 대한 기록을 남기려면 댓글종류 R, M 상관없이 모두 해당되는거죠?

**Comment by loveAlakazam** [comment]
@godboy4256 
댓글 데이터를 마이페이지와 연동하는 작업에서 전달드려야할 사항이 있습니다.

[전달사항]
댓글작성날짜(created_at)은 데이터베이스에서는 UTC 타임존 기준으로 되어있어서
날짜계산은 프론트에서 해주시는게 좋을거같습니다. 
UTC 타임존 기준으로, `현재날짜 - 댓글생성날짜` 차이로 나타내면 될거같습니다.

날짜가 년/월/일 전체표기라면 UTC -> KST 타임존을 변경해야되지만 위의 UI상에서는 UTC포맷으로 해도
현재날짜로부터 차이를 나타내기때문에 UTC포맷으로도 시간차이계산을 하면 되기때문입니다.

---

댓글작성날짜가 현재를 기준으로 1일이지나면 1일전 으로 표기되는것은 이해했습니다만 
여기에 대한 디테일한 궁금한점이 생겼는데요.

[질문] 댓글작성 날짜와 현재 날짜가 동일한 경우에는 어떻게 표기되나요?
- 1초전 / 1분전 / 1시간전 시간차이로 표기가 되나요?
- 현재 날짜와 시간정보를 나타내나요? (이런경우에는 UTC -> KST 로 타임존 전환이 필요합니다)

**Comment by godboy4256** [comment]
@loveAlakazam 

1. 넵 컨텐츠 날짜 계산 UTC 타임존 기준으로 주시면 프론트엔드에서 하도록 하겠습니다.

[질문 답변]
1. 네 맞습니다.
2. 시간 차이로 표기하려고 합니다.

**Comment by loveAlakazam** [comment]
방금 의 경우는 작성1분 이하일때 표기하는게 좋을거같네요

**Comment by godboy4256** [comment]
@loveAlakazam 

넵 알겠습니다. 그게 좀 더 깔끔하겠네요.
